### ISSUE TITLE
de-prioritize this plugin?

### ISSUE THREAD

**Issue by devenator** [back-to/generic#10]
Hi, is there any way to make this the last plugin tried? i.e zattoo does not work anymode when generic.py is loaded. After reading Issue #1  , I've try'd messing around, changing the priority to be always NO_PRIORITY, and even changed the name (in the code) to zzzgeneric; it get's listed by --plugins as the last in the list, but is still used in front of zattoo...

Any hints? If it is simply not possible beause of the way streamlink uses the priority, could you post an example how to modify streamlink.py so if it fails [with default values], it tries a second time with a --plugin-dirs option? I currently use this as a workaround

                streamlink -Q -O "$1" best
                        if [ $? -ne 0 ]; then
                streamlink --plugin-dirs /usr/lib/streamlink-generic/plugins/ -Q -O "$1" best
                        fi

but this is pretty slow because it completely loads everything a second time

in any case, thanks a lot for this plugin ;)

**Comment by back-to** [comment]
> Hi, is there any way to make this the last plugin tried?

it is already

> i.e zattoo does not work anymode when generic.py is loaded.

Zattoo changed some of there urls, not all might work with Streamlink yet

https://github.com/streamlink/streamlink/pull/2646

> changing the priority to be always NO_PRIORITY,

no need to change, it is already

> Any hints? If it is simply not possible beause of the way streamlink uses the priority,

show me a debug log `streamlink -l debug https://zattoo.com/watch/zdf worst`

> could you post an example how to modify streamlink.py so if it fails [with default values], it tries a second time with a --plugin-dirs option?

there is no need for this, show me your commands what you are actually doing and maybe your config file
