### ISSUE TITLE
Archives

### ISSUE THREAD

**Issue by Damianonymous** [back-to/generic#16]
Hello. I added your plugin to my archive of removed plugins, hope that's not a problem? I am not a developer, I try to include updates found by people, if you find a moment you can take a look.

https://github.com/Damianonymous/streamlink-plugins

**Comment by johnthecracker** [comment]
This is working plugin.
You don't benefit in any way in copying it from A to B.
Get missing plugins like fc2 if you can.
Japs are kamikaze and change website often. I have to manage without the plugin
and asking here for an update, knowing interest in "NSFW" is low.
