### ISSUE TITLE
Streams from parsatv.com only load after visiting page in browser

### ISSUE THREAD

**Issue by kronoc** [back-to/generic#17]
Thanks for a great plugin, which does a great job on many sites.

I am having some difficulty with https://www.parsatv.com

When I run streamlink on a page from the site *without* first visiting the page in a browser the following happens:

_streamlink https://www.parsatv.com/name=3sat#deutch best_ 

> [cli][info] Found matching plugin generic for URL https://www.parsatv.com/name=3sat#deutch 
> [plugins.generic][info] Version 2021-09-05 - https://github.com/back-to/generic 
> [plugins.generic][info]   1. URL=https://www.parsatv.com/name=3sat#deutch 
> [plugins.generic][info] Found Playlists: 1 (valid) 
> error: No playable streams found on this URL: https://www.parsatv.com/name=3sat#deutch 

However, if I visit the same page in a browser and then run the same command again:

_streamlink https://www.parsatv.com/name=3sat#deutch best_

> [cli][info] Found matching plugin generic for URL https://www.parsatv.com/name=3sat#deutch
> [plugins.generic][info] Version 2021-09-05 - https://github.com/back-to/generic
> [plugins.generic][info]   1. URL=https://www.parsatv.com/name=3sat#deutch
> [plugins.generic][info] Found Playlists: 1 (valid)
> [cli][info] Available streams: 576p (worst, best)
> [cli][info] Opening stream: 576p (hls)
> [cli][info] Starting player: /usr/bin/vlc

When I run the plugin with debug output I can see the m3u8 link in the html source on line 3790 in javascript where the variable name "file" points at the url - when I put this url directly into VLC it plays.

Thanks again for a great plugin, I can help with more debugging if you have a suggestion on how to make this work.

I normally use streamlink with tvheadend so ideally I would not be hitting a browser before hitting a stream.

**Comment by back-to** [comment]
> However, if I visit the same page in a browser and then run the same command again:

can't reproduce it

update Streamlink and use the debug loglevel `-l debug`

**Comment by kronoc** [comment]
Thanks, I can see a 403 error when debug is enabled 

streamlink -l debug https://www.parsatv.com/name=3sat#deutch best

[cli][debug] OS:         Linux-4.15.0-162-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.parsatv.com/name=3sat#deutch
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin generic for URL https://www.parsatv.com/name=3sat#deutch
[plugins.generic][info] Version 2021-09-05 - https://github.com/back-to/generic
[plugins.generic][info]   1. URL=https://www.parsatv.com/name=3sat#deutch
[plugins.generic][debug] Found Playlists: 1
[plugins.generic][debug] List length: 1 (with duplicates)
[plugins.generic][info] Found Playlists: 1 (valid)
[utils.l10n][debug] Language code: en_IE
[plugins.generic][debug] Skip HLS with error Unable to open URL: https://s4.hopslan.com:443/3sat/index.m3u8?token=e9ef125ad5bca4ba8691dcf296eddb4df19f0a60-e5ce6625db47fccf9fbbccf9fe923a30-1636749623-1636738823 (403 Client Error: Forbidden for url: https://s4.hopslan.com:443/3sat/index.m3u8?token=e9ef125ad5bca4ba8691dcf296eddb4df19f0a60-e5ce6625db47fccf9fbbccf9fe923a30-1636749623-1636738823)
error: No playable streams found on this URL: https://www.parsatv.com/name=3sat#deutch

**Comment by kronoc** [comment]
Once I hit the URL in a browser the 403 error goes away and it plays fine.

**Comment by WolfganP** [comment]
Look in your browser console for the request for the playlist, it may have an specific header field for Origin or Referer, add it to streamlink's command line with --http-header. 
Most of the times it work that way...

**Comment by back-to** [comment]
there are some `cloudflare` code on this site, which might be needed.

`/cdn-cgi/challenge-platform/h/g/scripts/invisible.js`
`CF$cv$params`

but the generic plugin won't work with this.

**Comment by kronoc** [comment]
Thanks for investigating, I'm going to have a go at a plug-in for this.
