### ISSUE TITLE
AlJazeera

### ISSUE THREAD

**Issue by johnthecracker** [back-to/generic#2]
[cli][info] Found matching plugin generic for URL https://www.aljazeera.com/live/
[plugin.generic][info] Version 2018-10-03 - https://github.com/back-to/generic
[plugin.generic][info]   1. URL=https://www.aljazeera.com/live/
[plugin.generic][info] --- IFRAMES ---
[plugin.generic][info] 1 - https://players.brightcove.net/665003303001/SkrZHHcl_default/index.html?videoId=5467349513001
[plugin.generic][info] 2 - https://www.youtube.com/embed/live_stream?channel=UCNye-wNBqNL5ZzHSJj3l8Bg&amp;autoplay=1&amp;modestbranding=1&amp;rel=0&amp;showinfo=0&amp;color=white&amp;fs=1
[plugin.generic][info] --- IFRAMES ---
Choose an iframe number from above: 2
[plugin.youtube][error] Could not get video info: Video unavailable
error: No playable streams found on this URL: https://www.aljazeera.com/live/
Press any key to continue . . .

Strange.

I get it like this:

;	YOUTUBE
#include <AutoItConstants.au3>
$url = "https://www.youtube.com/embed/live_stream?channel=UCNye-wNBqNL5ZzHSJj3l8Bg"
$iPID = Run(@ComSpec & ' /c curl.exe -k ' & $url,'',@SW_HIDE,$STDOUT_CHILD)
ProcessWaitClose($iPID)
$s = StdoutRead($iPID)
$s = StringTrimLeft($s,StringInStr($s,'href="https://www.youtube.com/watch?v=')+5)
$s = StringTrimRight($s,(StringLen($s)+1)-StringInStr($s,'"'))
ShellExecute('streamlink.exe','--http-no-ssl-verify --player=mpv.exe ' & $s & ' 480p','','',@SW_MINIMIZE)

<a href='https://postimg.cc/9D5NPhkG' target='_blank'><img src='https://i.postimg.cc/9D5NPhkG/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>

**Comment by back-to** [comment]
the **youtube plugin** mismatches the video_id as `live_stream`,
because the embedded livestream URL is currently not supported.

Ref https://github.com/streamlink/streamlink/pull/2113

---

there is also `aljazeeraen.py` for the `players.brightcove.net` link

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/aljazeeraen.py

**Comment by johnthecracker** [comment]
I removed aljazeera plugin from plugins directory, then checked how generic works.

It worked in choice 1, not in 2.

This is how I normally watch AlJazeera:

;	ALJAZERA
$url = 'http://aljazeera-eng-hd-live.hls.adaptive.level3.net/aljazeera/english2/index1296.m3u8'
ShellExecute('mpv.exe','--vf=scale=854:480 ' & $url)

**Comment by back-to** [comment]
> then checked how generic works.

you can use `streamlink generic://URL` to set a **high priority** and bypass streamlink plugins for  the first URL, if there is an iframe it will use the normal prioritys again.

---

This youtube URL will work with the **dev** version of streamlink

or with the latest `youtube.py`

https://raw.githubusercontent.com/streamlink/streamlink/159d30ffb12192c1fc071239f68688089fa2fe7f/src/streamlink/plugins/youtube.py

**Comment by johnthecracker** [comment]
When you say dev version is it nightly for windows or something else?

This is the best I can find:

https://bintray.com/streamlink/streamlink-nightly/streamlink#release

2018.10.01 (Oct 01, 2018)
