### ISSUE TITLE
hls stream and websocket protocol

### ISSUE THREAD

**Issue by johnthecracker** [back-to/generic#3]
https://www.streamago.com/#/livenow

https://www.streamago.com/#/chat/33619/9070894

```
C:\>streamlink.exe --http-no-ssl-verify --stream-sorting-excludes ">720p" "https://www.streamago.com/#/chat/33619/9070894" best,best-unfiltered
[cli][info] Found matching plugin generic for URL https://www.streamago.com/#/chat/33619/9070894
[plugin.generic][info] Version 2018-12-02 - https://github.com/back-to/generic
[plugin.generic][info]   1. URL=https://www.streamago.com/#/chat/33619/9070894
error: No plugin can handle URL: https://www.streamago.com/#/chat/33619/9070894
```
generic plugin cannot detect playlist.m3u8. Is this because playlist.m3u isn't in html source ?
I assume it is behind websocket link.
I get it with http sniffer if I change browser's user agent to iphone.

https://watch-live.streamago.tv/livecf/watch-live-039/032122c4-2404-4d54-a65c-cc6b4c71da56/playlist.m3u8

```
C:\>streamlink.exe --http-no-ssl-verify --stream-sorting-excludes ">720p" "https://watch-live.streamago.tv/livecf/watch-live-038/69120a83-c319-4d26-af5a-eddab87f25eb/playlist.m3u8" best,best-unfiltered
[cli][info] Found matching plugin hls for URL https://watch-live.streamago.tv/livecf/watch-live-038/69120a83-c319-4d26-af5a-eddab87f25eb/playlist.m3u8
[cli][info] Available streams: 640p (worst, best)
[cli][info] Opening stream: 640p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
```
With either iphone or firefox user agent there is always websocket link present:

https://new-message.streamago.tv/socket.io/?EIO=3&transport=websocket&sid=oZtudnlprhj8QQc_AODc
https://watch-live-007.streamago.tv/webrtc-session.json

Would it be possible for generic plugin to get hls stream hidden behind websocket link,
or there is streamlink plugin for specific website mandatory ?

**Comment by back-to** [comment]
> Would it be possible for generic plugin to get hls stream hidden behind websocket link,

this is **out of scope** for the generic plugin

---

you will need a plugin for this or use there api url directly
but you don't need a websocket.


If you want the api url,
change `USERID` with the number after `chat` from the original url

```
https://new-api.streamago.com/stream-api/streams?orderBy[0]=-createdAt&search[userId][0]=USERID
```

this url can be used with the generic but it might detect vods and livestreams
but you can block the vods with
`--generic-blacklist-filepath ".mp4"` or `--generic-blacklist-netloc "watch-replay.streamago.tv"`
