### ISSUE TITLE
CNC World Live Broadcast

### ISSUE THREAD

**Issue by johnthecracker** [back-to/generic#4]
http://www.xinhuanet.com/2015wlds/enindex.htm

There isn't much to see in html source, I looked at 2 links and cannot get it working.
This is something that works in unique Chinese way, and may be a candidate for generic plugin. 
You decide.

First link returns error 404:

'<source src="http://livecdn1.news.cn/cncen_mobile/manifest.m3u8"'

Second link is to "bravoplayer" 

<iframe id="ifrPcVideo" src="http://livecdn1.news.cn/www/cncen.html"

bravoPayer.runPlayer({
                api: "http://livecdn1.news.cn",
                type: "live",
                core: "http://livecdn1.news.cn/www/plugins/p2pcore.swf",
                cid: "live",
                default_stream: "sd13",
                sd:"sd13",
				ld:"sd13",
                isPlayAd:"0",
                tracker:"0",

"Content-Type:" is video/x-flv

http://livecdn1.news.cn/sd13/2019-03-06/06/1ed52346-0678.f4v
http://livecdn1.news.cn/sd13/2019-03-06/06/1ed52347-0679.f4v
http://livecdn1.news.cn/sd13/2019-03-06/06/1ed52348-0680.f4v

**Comment by back-to** [comment]
> and may be a candidate for generic plugin

the hls/m3u8 url is invalid which is an issue on there website,
and the rtmp/flash stream is not supported with this plugin.
